# Generated by Django 6.0.6 on 2026-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_chat_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='friend_request', max_length=20),
        ),
    ]
