# Generated by Django 6.0.6 on 2026-06-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
